### ISSUE TITLE
Problem:  timeouts preventing transfers from starting

### ISSUE THREAD

**Issue by jhsimpson** [artefactual/archivematica#712]
Changes introduced into the qa/1.x branch in #531  (updated in #565) have changed the way http requests are working.  This is affecting the ability to start large transfers.

The communication between the dashboard and the storage service is synchronous - when a user clicks the 'start transfer' button - the dashboard sends an http request to the storage service to copy files to the activeTransfers watched Directories.   The request blocks until the storage service completes the process of moving the files around.  For large this this can take several minutes.

Ideally the  storage service would be modified to support asynchronous calls (accept a callback with the  original request, send 201, and call the callback when the work is completed).   For the 1.7.0 release, it may be necessary to revert the #531 change.

**Comment by sevein** [comment]
Fixed in https://github.com/artefactual/archivematica/pull/747.

**Comment by sromkey** [comment]
@currmie I believe @ross-spencer might have some advice on how to qa this (e.g. how to generate a large transfer)

**Comment by currmie** [comment]
Verification status: I can start large file transfers but tests still fail, this time during the Index AIP job.
